# to build image:
# > docker-compose build

# to run container (and keep atached to the container)
# > docker-compose up [<service_name>]

# to run container as a daemon
# > docker-compose up -d [<service_name>]
# to attach to daemon container
# > docker exec -it <container_id> bash

# to stop the started container
# > docker-compose stop [<service_name>]

# to stop and remove the started container
# > docker-compose down [<service_name>]

version: "3"
services:
  portic_front:
    image: portic_front
    container_name: portic_front
    restart: always
    tty: true
    build:
      context: ..
      dockerfile: docker/portic_front.Dockerfile
    volumes:
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        - ./nginx/proxy_params:/etc/nginx/proxy_params      
    ports:
        - $NGINX_HTTP_PORT:80
    # logging:
    #  driver: "syslog"
    #  options:
    #    tag: "tryasport"
